apiVersion: v1
kind: Service
metadata:
  name: angular-network
  labels:
    app: angular-app
spec:
  selector:
    app: angular-app
  ports:
    - port: 80
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: express-network
  labels:
    app: express-app
spec:
  selector:
    app: express-app
  ports:
    - port: 3000


---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
